version: '3.7'

services:

  # Backend API
  movieholic-api:
    container_name: backend
    build: ./
    command: npm run dev
    working_dir: /usr/src/movieholic-api
    environment:
      mongoURI: mongodb://localhost:27017/movieholic
      REDIS_URI: redis://redis:6379
    links:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/movieholic-api

  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
