version: '3.7'

services:

  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"

  # Backend API
  movieholic-api:
    container_name: backend
    build: ./
    command: npm run start
    working_dir: /usr/src/movieholic-api
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/movieholic-api
