version: '3.7'

services:

  # Backend API
  movieholic-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/movieholic-api
    environment:
      mongoURI: mongodb://localhost:27017/movieholic
    links:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/movieholic-api

  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
